export const Attendees = {
    namespaced: true,

    state: {
        burgersBeerAndBBQ: [
            { name: 'Bjorn', linnen: 'nee', diet: 'nee' },
            { name: 'Eline', linnen: 'ja', diet: 'nee' },
            { name: 'Tim D.', linnen: '', diet: '' },
            { name: 'Johan', linnen: '', diet: '' },
            { name: 'Jos', linnen: '', diet: '' },
            { name: 'Rins', linnen: '', diet: '' },
            { name: 'Leonidas', linnen: '', diet: '' },
            { name: 'Rens van H.', linnen: '', diet: '' },
            { name: 'Roos van H.', linnen: '', diet: '' },
            { name: 'Martine', linnen: '', diet: '' },
            { name: 'Danielle', linnen: '', diet: '' },
            { name: 'Tim H.', linnen: '', diet: '' },
            { name: 'Richard', linnen: '', diet: '' },
            { name: 'Roel', linnen: '', diet: '' },
            { name: 'Mohammed', linnen: '', diet: '' },
            { name: 'Hein van B.', linnen: '', diet: '' },
            { name: 'Jill', linnen: '', diet: '' },
            { name: 'Sascha', linnen: '', diet: '' },
            { name: 'Willie', linnen: '', diet: '' },
            { name: 'André', linnen: '', diet: '' },
            { name: 'Bryan', linnen: '', diet: '' },
            { name: 'Evelien', linnen: '', diet: '' },
            { name: 'Kick', linnen: '', diet: '' },
        ],
        coffeeAndCake: [
            { name: 'Bjorn', diet: 'nee' },
            { name: 'Eline', diet: 'nee' },
            { name: 'Gerard', diet: '' },
            { name: 'Wilma', diet: '' },
            { name: 'Lya', diet: '' },
            { name: 'Ria', diet: '' },
            { name: 'Frans', diet: '' },
            { name: 'Els', diet: '' },
            { name: 'Dick', diet: '' },
            { name: 'Patricia', diet: '' },
            { name: 'Thijmen', diet: '' },
            { name: 'Kaj', diet: '' },
        ],
        winingAndDining: [
            { name: 'Bjorn', linnen: 'nee', diet: 'nee' },
            { name: 'Eline', linnen: 'ja', diet: 'nee' },
            { name: 'Dumont', linnen: '', diet: '' },
            { name: 'Linda', linnen: '', diet: '' },
            { name: 'Martien', linnen: '', diet: '' },
            { name: 'Marlie', linnen: '', diet: '' },
            { name: 'MaMieke', linnen: '', diet: '' },
            { name: 'Mariska', linnen: '', diet: '' },
            { name: 'Boaz', linnen: '', diet: '' },
            { name: 'Edwin', linnen: '', diet: '' },
            { name: 'Femke', linnen: '', diet: '' },
            { name: 'Robijn', linnen: '', diet: '' },
            { name: 'Jelle', linnen: '', diet: '' },
            { name: 'Bertine', linnen: '', diet: '' },
            { name: 'Ramon', linnen: '', diet: '' },
            { name: 'Jurre', linnen: '', diet: '' },
            { name: 'Anne', linnen: '', diet: '' },
            { name: 'Hanneke', linnen: '', diet: '' },
            { name: 'Janna', linnen: '', diet: '' },
            { name: 'Alba', linnen: '', diet: '' },
            { name: 'Tim H.', linnen: '', diet: '' },
            { name: 'Judith', linnen: '', diet: '' },
            { name: 'Rens van B.', linnen: '', diet: '' },
            { name: 'Nathalie', linnen: '', diet: '' },
            { name: 'Billie', linnen: '', diet: '' },
        ],
        bikesAndBeers: [
            { name: 'Bjorn', rental: 'ja', tandem: 'ja' },
            { name: 'Eline', rental: 'ja', tandem: 'Bjorn' },
            { name: 'Linda', rental: 'Volle bak huren die handel.', tandem: 'Tandems. Alleen maar tandems.' },
            { name: 'Dumont', rental: '', tandem: '' },
        ]
    },

    mutations: {},
    actions: {}
}
