export const Attendees = {
    namespaced: true,

    state: {
        burgersBeerAndBBQ: [
            { name: 'Bjorn', linnen: 'nee', diet: 'nee' },
            { name: 'Eline', linnen: 'nee', diet: 'nee' },
            { name: 'André', linnen: 'ja', diet: 'nee' },
            { name: 'Leonidas', linnen: '', diet: '' },
            { name: 'Bryan', linnen: '', diet: '' },
            { name: 'Tim H.', linnen: '', diet: '' },
            { name: 'Evelien', linnen: '', diet: '' },
            { name: 'Danielle', linnen: 'ja', diet: '' },
            { name: 'Wil C.', linnen: '', diet: '' },
            { name: 'Dennis', linnen: '', diet: '' },
            { name: 'Jos', linnen: '', diet: '' },
            { name: 'Harm', linnen: '', diet: '' },
            { name: 'Roos', linnen: '', diet: '' },
            { name: 'Martine', linnen: '', diet: '' },
            { name: 'Jelle', linnen: '', diet: '' },
            { name: 'Robijn', linnen: '', diet: '' },
            { name: 'Femke', linnen: '', diet: '' },
            { name: 'Edwin  ', linnen: '', diet: '' },
            { name: 'Richard  ', linnen: '', diet: '' },
            { name: 'Johan  ', linnen: '', diet: '' },
            { name: 'Rins  ', linnen: '', diet: '' },
        ],
        coffeeAndCake: [
            { name: 'Bjorn', diet: 'nee' },
            { name: 'Eline', diet: 'nee' },
            { name: 'Marlie', diet: '' },
            { name: 'Martien', diet: '' },
            { name: 'Wil C.', diet: '' },
            { name: 'Lya', diet: '' },
            { name: 'Els', diet: '' },
            { name: 'Dick', diet: '' },
            { name: 'Anne', diet: '' },
            { name: 'Jurre', diet: '' },
            { name: 'Gerard', diet: '' },
            { name: 'Wilma', diet: '' },
            { name: 'Jelle', diet: '' },
            { name: 'Robijn', diet: '' },
            { name: 'Femke', diet: '' },
            { name: 'Edwin', diet: '' },
        ],
        winingAndDining: [
            { name: 'Bjorn', linnen: 'nee', diet: 'nee' },
            { name: 'Eline', linnen: 'nee', diet: 'nee' },
            { name: 'André', linnen: 'nee', diet: 'nee' },
            { name: 'Hanneke', linnen: '', diet: '' },
            { name: 'Alba', linnen: '', diet: '' },
            { name: 'Janna', linnen: '', diet: '' },
            { name: 'Tim H.', linnen: '', diet: '' },
            { name: 'Judith', linnen: '', diet: '' },
            { name: 'MaMieke', linnen: '', diet: '' },
            { name: 'Rens van H.', linnen: '', diet: '' },
            { name: 'Mariska', linnen: '', diet: '' },
            { name: 'Boaz', linnen: '', diet: '' },
            { name: 'Marlie', linnen: '', diet: '' },
            { name: 'Martien', linnen: '', diet: '' },
            { name: 'Linda', linnen: 'ja', diet: '' },
            { name: 'Dumont', linnen: 'ja', diet: '' },
            { name: 'Wil C.', linnen: '', diet: '' },
            { name: 'Jelle', linnen: '', diet: '' },
            { name: 'Robijn', linnen: '', diet: '' },
            { name: 'Femke', linnen: '', diet: '' },
            { name: 'Edwin', linnen: '', diet: '' },
        ],
        bikesAndBeers: [
            { name: 'Bjorn', rental: 'ja', tandem: 'ja' },
            { name: 'Eline', rental: 'ja', tandem: 'Bjorn' },
            { name: 'André', rental: 'ja', tandem: 'nee' },
            { name: 'Marlie', rental: 'nee', tandem: '' },
            { name: 'Martien', rental: 'nee', tandem: '' },
            { name: 'Linda', rental: 'nee', tandem: '' },
            { name: 'Dumont', rental: 'nee', tandem: '' },
        ]
    },

    mutations: {},
    actions: {}
}
